title: Dennis Nyaaba 
logo: IMG-20230808-WA0012.jpg
description: This repo is about analysis made on Ecommerse csv data from kaggle dataset website 

show_dowloads: true

theme: jekyll-theme-modernist
